pod:
  name: front-end
  image:
    repository: {{DOCKER_REPO}}/{{APP_NAME}}
    tag: {{DOCKER_TAG}}
  ports:
    containerPort: 5000
  
service:
  type: NodePort
  port: 443
  targetPort: 5000
  nodePort: 30443

ingress:
  host: {{HOST_NAME}}

namespace: {{APP_NAME}}-ns

certManager:
  enabled: true
  issuer: {{APP_NAME}}-ss
  certificate:
    name: {{APP_NAME}}-ca-cert
    secretName: {{APP_NAME}}-ca-cert-secret
    commonName: {{APP_NAME}}-ca
