apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certManager.certificate.name }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.certManager.certificate.secretName }}
  isCA: true
  commonName: {{ .Values.certManager.certificate.commonName }}
  issuerRef:
    name: {{ .Values.certManager.issuer }}
    kind: Issuer