apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-{{ .Values.pod.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.pod.name }}
spec:
  containers:
  - name: {{ .Release.Name }}-{{ .Values.pod.name }}
    image: "{{ .Values.pod.image.repository }}:{{ .Values.pod.image.tag }}"
    ports:
    - containerPort: {{ .Values.pod.ports.containerPort }}
