apiVersion: v2
name: crypto-app
description: A Helm chart web-app
version: 0.1.0
appVersion: "1.0"
type: application

keywords:
  - pod
  - service
  - nodeport
  - kubernetes

maintainers:
  - name: Almog Levi
    email: almog.levig@gmail.com

sources:
  - https://github.com/AlmogLevig/saas_application/